### ISSUE TITLE
erorr when runing the code.

### ISSUE THREAD

**Issue by AradAlter** [lopotras/WoltPartner-Schedule#9]
first of all thank you, in Israel the scheduled hours are different and the shifts open usually on a Tuesday at 16:00 but that sometimes changed, how can i adapt to the changes and the error is because of the difference? thank you .
![image](https://user-images.githubusercontent.com/82899944/115437522-f5b11180-a214-11eb-8f7d-b611b362ce9d.png)
![image](https://user-images.githubusercontent.com/82899944/115437575-02ce0080-a215-11eb-9a95-4dc268d7c65a.png)
![image](https://user-images.githubusercontent.com/82899944/115437605-0d889580-a215-11eb-8cab-2e8799c000fb.png)

**Comment by lopotras** [comment]
Hi @AradAlter, thank you for the feedback.

First the version of Python you need to run the code is 3.8.5 which is available [here](https://docs.conda.io/en/latest/miniconda.html) under _Python 3.8_.

Second, you will need to activate python, which is explained [here](https://conda.io/activation ).

The you can open the file with correct python version 
![image](https://user-images.githubusercontent.com/63056046/116068176-3cc25b00-a68a-11eb-84f2-ce681c3a4ccb.png)

As to all the shifts appearing on one day, it is still a work in progress done mostly in [this issue](https://github.com/lopotras/WoltPartner-Schedule/issues/6). If that is the case for you, [this version](https://github.com/lopotras/WoltPartner-Schedule/tree/munich) is aiming to tackle the compatibility with all the shifts appearing at once. 

Unfortunately, because that is not the case in my city and for some reason the application itself has a few differences (depending on I really don't know what), I cannot test all changes on my computer. I am happy to try and fix the problems if you can provide me pictures or screen recordings showing what is happening though.

Let me know how it works!

**Comment by lopotras** [comment]
Closing the issue — it's similar to [this one](https://github.com/lopotras/WoltPartner-Schedule/issues/6).
